{"time":"2024-11-07T16:09:54.8070185+08:00","level":"INFO","msg":"using version","core version":"0.18.5"}
{"time":"2024-11-07T16:09:54.8070185+08:00","level":"INFO","msg":"created symlink","path":"D:\\Desktop\\hw4\\wandb\\run-20241107_160954-qbghg0nn\\logs\\debug-core.log"}
{"time":"2024-11-07T16:09:54.926868+08:00","level":"INFO","msg":"created new stream","id":"qbghg0nn"}
{"time":"2024-11-07T16:09:54.926868+08:00","level":"INFO","msg":"stream: started","id":"qbghg0nn"}
{"time":"2024-11-07T16:09:54.926868+08:00","level":"INFO","msg":"sender: started","stream_id":"qbghg0nn"}
{"time":"2024-11-07T16:09:54.926868+08:00","level":"INFO","msg":"handler: started","stream_id":{"value":"qbghg0nn"}}
{"time":"2024-11-07T16:09:54.926868+08:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"qbghg0nn"}}
{"time":"2024-11-07T16:10:12.283956+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": EOF"}
{"time":"2024-11-07T16:10:35.6909223+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:11:01.4425791+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:11:25.6747708+08:00","level":"INFO","msg":"stream: closing","id":"qbghg0nn"}
{"time":"2024-11-07T16:11:25.6747708+08:00","level":"INFO","msg":"handler: closed","stream_id":{"value":"qbghg0nn"}}
{"time":"2024-11-07T16:11:25.6747708+08:00","level":"INFO","msg":"writer: Close: closed","stream_id":{"value":"qbghg0nn"}}
{"time":"2024-11-07T16:11:25.6747708+08:00","level":"ERROR","msg":"sender: upsertRun:","error":"failed to upsert bucket: api: failed sending: POST https://api.wandb.ai/graphql giving up after 4 attempt(s): context canceled"}
{"time":"2024-11-07T16:11:25.6747708+08:00","level":"ERROR","msg":"runwork: ignoring record after close","work":{"Record":{"RecordType":{"Request":{"RequestType":{"Defer":{}}}},"control":{"always_send":true}}}}
{"time":"2024-11-07T16:11:25.6763308+08:00","level":"INFO","msg":"sender: closed","stream_id":"qbghg0nn"}
{"time":"2024-11-07T16:11:25.6763308+08:00","level":"INFO","msg":"stream: closed","id":"qbghg0nn"}
